# Generated by Django 4.1.7 on 2023-05-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_order_pizza_size_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type_name', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pizza_photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='weight',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='quantity',
            field=models.IntegerField(default=12, verbose_name='количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='main.pizzatype'),
            preserve_default=False,
        ),
    ]
