# Generated by Django 4.1.7 on 2023-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pizzatype_remove_order_quantity_remove_pizza_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
