# Generated by Django 4.1.7 on 2023-05-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
    ]
