# Generated by Django 4.1.7 on 2023-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pizza_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='price',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
