# Generated by Django 4.1.7 on 2023-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_price_order_total_price_pizzatype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_size',
            field=models.CharField(max_length=250),
        ),
    ]
