# Generated by Django 4.1.7 on 2023-05-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_pizza_pizza_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='количество'),
        ),
    ]
