# Generated by Django 4.1.7 on 2023-05-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_pizza_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('in-transit', 'in-transit'), ('delivered', 'delivered')], default='pending', max_length=30),
        ),
    ]
