# Generated by Django 4.1.7 on 2023-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatype',
            name='description',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
